version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: racing_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: racing
      MYSQL_USER: racing
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - racing_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - racing_network

  web:
    build: .
    container_name: racing_web
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_HOST: db
      DB_NAME: racing
      DB_USER: racing
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
    volumes:
      - .:/app
      - racing_static:/app/staticfiles
      - racing_media:/app/media
    depends_on:
      - db
    networks:
      - racing_network

  nginx:
    image: nginx:alpine
    container_name: racing_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - racing_static:/app/staticfiles
      - racing_media:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - racing_network

volumes:
  racing_db_data:
  racing_static:
  racing_media:

networks:
  racing_network:
    driver: bridge